### ISSUE TITLE
Add Updoots to RealTalk Entries

### ISSUE THREAD

**Issue by Rodrigo400** [prosperoa/RealTalkDiscordBot#3]
As a user, I would like updoots to be implemented for RealTalk entries. The up arrow can be utilized to represent updoots. All discord users can updoot. Updoots will help show highly rated quotes.

Implement the ability to find the most highly rated updooted RealTalk entry of a user and post to the client.

**Comment by prosperoa** [comment]
That's kinda dope, ngl.
This project is open source tho, get to coding.

**Comment by prosperoa** [comment]
Implemented in https://github.com/prosperoa/RealTalkDiscordBot/commit/5842ae1a11d772e4782ac907a2deac74e2eea6da
